routes/web.php
<?php

use Bittacora\ContentMultimedia\Http\Controllers\ContentMultimediaController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel')->middleware(['web', 'auth','admin-menu'])->name('content-multimedia.')->group(function(){
    Route::post('content-multimedia/reorder', [ContentMultimediaController::class, 'reorder'])->name('reorder');
    Route::post('content-multimedia/detach', [ContentMultimediaController::class, 'detach'])->name('detach');
});

resources/views/livewire/content-multimedia-images-widget.blade.php
<div class="widget-box widget-color-blue ui-sortable-handle mb-4" id="widget-box-7">
    <div class="widget-header widget-header-small">
        <h6 class="widget-title smaller">Imágenes adjuntas</h6>
    </div>
    <div class="widget-body">
        <div class="widget-main">
            @if(!is_null($images))
                <table data-content-id="{{$contentId}}" id="contentMultimediaImagesWidgetTable" class="mb-0 table table-borderless table-bordered-x brc-secondary-l3 text-dark-m2 radius-1 overflow-hidden">
                    <thead>
                    <tr>
                        <th class="text-center w-10">Imagen</th>
                        <th class="w-30">Título</th>
                        <th class="text-center w-20">Posición</th>
                        <th class="text-center w-10">Orden</th>
                        <th class="text-center w-10">Activo</th>
                        <th class="text-center w-10">Destacado</th>
                        <th class="text-center w-10"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($images as $image)
                        <tr id="{{$image->id}}" data-content-id="{{$image->content_id}}">
                            <td>
                                @livewire('utils::media-preview', ['media' => $image->multimedia->mediaModel()->first()])
                            </td>
                            <td>
                                @livewire('utils::model-translatable-attribute', ['model' => $image->multimedia, 'attribute' => 'title'])
                            </td>
                            <td>
                                @livewire('content-multimedia::content-multimedia-location-select', ['model' => $image, 'module' => 'page'])
                            </td>
                            <td class="dragHandle cursor">
                                <div class="d-flex justify-content-center align-items-center" style="pointer-events: none">
                                    <span class="align-items-center badge bgc-purple-d1 pos-rel text-white radius-4 px-3">
                                        <span class="bgc-primary-tp4 opacity-5 position-tl h-100 w-100 radius-4"></span>
                                        <span class="pos-rel">
                                            {{$image->order_column}}
                                        </span>
                                    </span>
                                </div>
                            </td>
                            <td class="text-center">
                                @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $image, 'value' => $image->active, 'size' => 'xxs'])
                            </td>
                            <td class="text-center">
                                @livewire('utils::datatable-default', ['fieldName' => 'featured', 'model' => $image, 'value' => $image->featured, 'size' => 'xxs'])
                            </td>
                            <td>
                                <div class="buttons d-flex">
                                    <a class="btn btn-xs btn-outline-danger button-detach" onclick="return confirm('¿Quieres desenlazar este recurso del contenido?')">
                                        <i class="fa fa-times"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <div class="alert alert-warning">
                    No hay imágenes adjuntas al contenido.
                </div>
            @endif
        </div>
    </div>
</div>

@push('scripts')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(document).ready(function() {
            // Initialise the table
            $("#contentMultimediaImagesWidgetTable").tableDnD({
                'onDrop': function(table, row){
                    console.log(row.rowIndex);
                    var rows = [];
                    console.log($(table).find('tr'));

                    $.each($(table).find("tbody").find("tr"), function(key, value){
                        rows[key+1] = $(value).attr('id');
                    });

                    $.ajax({
                        method: 'post',
                        url: "{{route("content-multimedia.reorder")}}",
                        data: {
                            'contentId':{{$contentId}},
                            'type' : 'I',
                            'rows' : rows
                        },
                        context: document.body
                    }).done(function(data) {
                        data = JSON.parse(data);

                        $.each(data, function(key, value){
                            $("tr#"+key).find(".pos-rel").text(value);
                        });
                    });
                },
                'onDragClass' : 'bg-info',
                'dragHandle' : '.dragHandle',
            });

            $("body").on("click", ".button-detach", function(){
                var id = $(this).parents('tr').attr('id');
                var row = $(this).parents('tr')[0].rowIndex;
                $.ajax({
                    method: 'post',
                    url: "{{route("content-multimedia.detach")}}",
                    data: {
                        'id':id,
                        'type':'I',
                        'contentId':$(this).parents('tr').data('content-id')
                    },
                    context: document.body
                }).done(function(data) {

                    if(data != 'error'){
                        $("tr#"+id).addClass("bg-danger");
                        setTimeout(function(){
                            $("tr#"+id).fadeOut(1000);
                            document.getElementById("contentMultimediaImagesWidgetTable").deleteRow(row);
                        },500);

                        data = JSON.parse(data);

                        $.each(data, function(key, value){
                            $("tr#"+key).find(".pos-rel").text(value);
                        });
                    }else{
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: 'El elemento no pudo ser eliminado del contenido',
                            showConfirmButton: false,
                            timer: 2000
                        });
                    }
                });
            });
        });
    </script>

@endpush

resources/views/livewire/content-multimedia-location-select.blade.php
<div class="position-relative">
    <select class="form-control content-multimedia-location-select" id="{{$model->id}}" wire:model="selectedValue" wire:change="changeLocation()">
        <option value="">-- Sin asignar --</option>
        @foreach($options as $option)
            <option value="{{$option->id}}">{{$option->name}}</option>
        @endforeach
    </select>
    <div class="w-100" wire:loading>
        <div class="bg-info text-white py-1 px-2 mt-1">
            <i class="fa fa-info-circle"></i> Modificando posición...
        </div>
    </div>

    @if (session()->has('message'))
        <div class="box-message-{{session()->get('message')['type']}} bg-{{session()->get('message')['type']}} text-white py-1 px-2 mt-1">
            <i class="{{session()->get('message')['icon']}}"></i> {{session()->get('message')['text']}}
        </div>
    @endif
</div>

@push('scripts')
    <script>
        setInterval(function(){
            $(".box-message-success").fadeOut(1000);
            $(".box-message-danger").fadeOut(1000);
        }, 1000);
    </script>
@endpush

resources/views/livewire/detach-multimedia-button.blade.php
<div>
    <div class="buttons d-flex">
        <a class="btn btn-xs btn-outline-danger button-detach" wire:click.prevent="deleteConfirmation({{$contentMultimediaId}}, '{{$type}}')">
            <i class="fa fa-times"></i>
        </a>
    </div>
</div>

@push('scripts')
    <script>
        window.addEventListener('swal', event => {
            Swal.fire({
                icon: event.detail.type,
                title: event.detail.title,
                text: event.detail.text,
                showConfirmButton: true,
                showCancelButton: true,
                confirmButtonText: 'Sí',
                cancelButtonText: 'Cancelar',
                confirmButtonColor: 'success'
            }).then((result) => {
                if(result.isConfirmed){
                    Livewire.emit('detachFile'+event.detail.filetype+event.detail.id, event.detail.id);
                }
            });
        });
    </script>
@endpush

resources/views/livewire/toggle-content-multimedia-button.blade.php
<div class="text-center">
    @if ($attached)
        <a class="btn btn-danger btn-xs mb-1"
           wire:click="toggleAttachment()"
           wire:loading.class="btn-warning"
           title="Desactivado">
            <i class="fa fa-minus" wire:loading.remove></i>
            <div wire:loading>
                <i class="fa fa-cog fa-spin fa-fw"></i>
            </div>
        </a>
    @else
        <a class="btn btn-success btn-xs mb-1"
           wire:click="toggleAttachment()"
           wire:loading.class="btn-warning"
           title="Activado">
            <i class="fa fa-plus" wire:loading.remove></i>
            <div wire:loading>
                <i class="fa fa-cog fa-spin fa-fw"></i>
            </div>
        </a>
    @endif
</div>

resources/views/livewire/upload-content-multimedia-widget.blade.php
<div class="widget-box widget-color-blue ui-sortable-handle mb-4" id="widget-box-7">
    <div class="widget-header widget-header-small">
        <h6 class="widget-title smaller">Añadir multimedia</h6>
    </div>
    <div class="widget-body">
        <div class="widget-main">
            @livewire('form::input-file', [
                'name' => $fieldName . '[]',
                'idField' => $fieldName,
                'fieldWidth' => 12,
                'required' => false,
                'accept' => $allowedFormats,
                'multiple' => $multiple,
                'allowedFileExtensions' => $allowedExtensions,
                'showUpload' => false,
                'showRemove' => true
            ])
            @if($errors->has($fieldName))
                <ul>
                    @foreach($errors->get($fieldName . '.*') as $errors)
                        @foreach($errors as $error)
                            <li class="text-danger">{{ $error }}</li>
                        @endforeach
                    @endforeach
                </ul>
            @endif
            @if($errors->has($fieldName . '.*'))
                <ul>
                    @foreach($errors->get($fieldName . '.*') as $errors)
                        @foreach($errors as $error)
                            <li class="text-danger">{{ $error }}</li>
                        @endforeach
                    @endforeach
                </ul>
            @endif
        </div>
    </div>
</div>